name: linkvault
description: Local-first bookmark manager with collections and tags.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  path_provider: ^2.1.2

  # DATABASE
  sqflite: ^2.4.2
  path: ^1.9.0

  # STATE
  flutter_riverpod: ^2.6.1

  # NETWORK
  http: ^1.2.2

  # IMAGES
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

  # SETTINGS
  shared_preferences: ^2.3.3

  #FORMATO DE FECHAS
  intl: ^0.19.0

  #PARA ABRIR ENLACES EN EL NAVEGADOR
  url_launcher: ^6.3.2

  #PREVIEW DE LINKS
  any_link_preview: ^3.0.3

  #PARA FUNCIONALIDAD DE RECIBIR ENLACES COMPARTIDOS DESDE OTRAS APLICACIONES
  #receive_sharing_intent: ^1.6.4
  share_handler: ^0.0.21

  #PARA EXPORTAR E IMPORTAR BASE DE DATOS EN FORMATO ZIP
  archive: ^3.6.1
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.13 #no hace falta actualmente

  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"